### PR TITLE
feat(docs): link the testnet deployment guide

### PR DESCRIPTION
**Pull request by SimonKraus**
add testnet deployment guide by @fakirAyoub

### CODE REVIEW

**Comment by vgantchev** [comment]
I have my doubts - this is currently irrelevant for HydraDX which runs as Relay Chain

**Comment by vgantchev** [comment]
Not really sure how the commit of @fakirAyoub landed on master :D

**Comment by SimonKraus** [comment]
Ayoub created a PR over here.
So it might be better included in the BSX Docs?

**Comment by vgantchev** [comment]
https://docs.bsx.fi/infra_testnet it's there already. Ayoub opened PR here but then we decided to move it to Basilisk. And we forgot to close the open PR :))

**Pull request closed without merging**
