### PR TITLE
Improve footer and remove unused link from header

### PR DESCRIPTION
**Pull request by vgantchev**

### CODE REVIEW

**Comment by SimonKraus** [comment]
Bildschirmfoto 2021-04-18 um 09 04 11

Added screenshot for preview. WDYT @jak-pan ?

**Comment by jak-pan** [comment]
Yeah let's stick with old color and the logo is ott. We should make it like half the size.

**Comment by vgantchev** [comment]
@SimonKraus you are on the wrong branch so your screenshot is off :)

**Comment by SimonKraus** [comment]
Bildschirmfoto 2021-04-18 um 12 17 41

maaaaan you should do some cleanup :D too many footer branches. 
remove when finished please.

**Comment by SimonKraus** [comment]
Bildschirmfoto 2021-04-18 um 12 23 07

this was the other footer branch

**Comment by vgantchev** [comment]
> Bildschirmfoto 2021-04-18 um 12 17 41
> 
> 
> 
> maaaaan you should do some cleanup :D too many footer branches. 
> 
> remove when finished please. 

the other "footer" branch belongs to a pr which we decides to keep open (snake theme). I will check if i can make logo smaller

**Pull request closed without merging**
