### PR TITLE
Add markdown link check to actions

### PR DESCRIPTION
**Pull request by vgantchev**
Resolves https://github.com/galacticcouncil/HydraDX-docs/issues/2

### CODE REVIEW

**Comment by vgantchev** [comment]
@jak-pan maybe you have ideas? The check is falling for all local URLs -can we somehow get the build running in the action? 

Another option would be to run the check post-deploy against docs.hydradx.io

**Comment by jak-pan** [comment]
I think we don't need this. Not sure why I added the issue (probably because the broken links with non / links, we could just check that) I guess the build checks if the links are ok?

**Comment by jak-pan** [comment]
So building in pipeline and checking if it passed should be enough

**Comment by vgantchev** [comment]
true and also quite obvious! closing the PR, you can close the issue

**Pull request closed without merging**
